// Page level action types
export const SET_PAGE_TITLE = "SET_PAGE_TITLE";

// Dealer related action types
export const SET_AUTHORIZATION = "SET_AUTHORIZATION";
export const SET_AUTHORIZED_DEALERIDS = "SET_AUTHORIZED_DEALERIDS";
export const SET_SELECTED_AUTHORIZED_DEALERID = "SET_SELECTED_AUTHORIZED_DEALERID";
export const SET_AUTHORIZED_DEALERS = "SET_AUTHORIZED_DEALERS";

// Orders related action types
export const SET_ORDER_LIST = "SET_ORDER_LIST";
export const SET_ORDER_LIST_SELECTED_FROMDATE = "SET_ORDER_LIST_SELECTED_FROMDATE";
export const SET_ORDER_LIST_SELECTED_TODATE = "SET_ORDER_LIST_SELECTED_TODATE";

// Order Details related action types
export const SET_SELECTED_ORDER_DETAIL = "SET_SELECTED_ORDER_DETAIL";
