export const SET_AUTHORIZATION = "SET_AUTHORIZATION";
export const SET_AUTHORIZED_DEALERIDS = "SET_AUTHORIZED_DEALERIDS";
export const SET_SELECTED_AUTHORIZED_DEALERID = "SET_SELECTED_AUTHORIZED_DEALERID";
export const SET_AUTHORIZED_DEALERS = "SET_AUTHORIZED_DEALERS";